const tipoAcao = [
  { acao: '4', nome: 'AÇÃO CAUTELAR' },
  { acao: '2', nome: 'AÇÃO DE COBRANÇA' },
  { acao: '20', nome: 'AÇÃO DE BUSCA E APREENSÃO' },
  { acao: '23', nome: 'AÇÃO DE EXIBIÇÃO DE DOCUMENTOS' },
  { acao: '52', nome: 'AÇÃO DE DEPOSITO' },
  { acao: '54', nome: 'AÇÃO DE REINTEGRAÇÃO DE POSSE' },
  { acao: '19', nome: 'AÇÃO DE OBRIGAÇÃO DE FAZER' },
  { acao: '53', nome: 'AÇÃO DE IMISSÃO NA POSSE' },
  { acao: '24', nome: 'AÇÃO DE PRESTAÇÃO DE CONTAS' },
  { acao: '21', nome: 'AÇÃO DE CONSIGNAÇÃO EM PAGAMENTO' },
  { acao: '12', nome: 'AÇÃO MONITÓRIA' },
  { acao: '5', nome: 'AÇÃO REVISIONAL' },
  { acao: '29', nome: 'CARTA PRECATÓRIA' },
  { acao: '3', nome: 'AÇÃO INDENIZATÓRIA / DECLARATÓRIA' },
  { acao: '50', nome: 'CRIMINAL' },
  { acao: '56', nome: 'CUMPRIMENTO DE SENTENÇA' },
  { acao: '13', nome: 'AÇÃO DE REPETIÇÃO DE INDÉBITO' },
  { acao: '27', nome: 'EMBARGOS MONITÓRIOS' },
  { acao: '14', nome: 'EMBARGOS DE TERCEIRO' },
  { acao: '26', nome: 'EMBARGOS À EXECUÇÃO' },
  { acao: '57', nome: 'EXECUÇÃO' },
  { acao: '7', nome: 'MANDADO DE SEGURANÇA' },
  { acao: '16', nome: 'NOTIFICAÇÃO EXTRAJUDICIAL' },
  { acao: '15', nome: 'OUTROS (ESPECIFICAR NO DETALHAMENTO DO OBJETO)' },
  { acao: '8', nome: 'FALÊNCIA' },
  { acao: '35', nome: 'HABILITAÇÃO DE CRÉDITO / IMPUGNAÇÃO' },
  { acao: '1', nome: 'PROCESSO ADMINISTRATIVO' },
  { acao: '11', nome: 'EXECUÇÃO FISCAL' },
  { acao: '10', nome: 'EXECUÇÃO DE TÍTULO EXTRAJUDICIAL' },
  { acao: '9', nome: 'RECUPERAÇÃO JUDICIAL' },
  { acao: '22', nome: 'TRABALHISTA' },
  { acao: '60', nome: 'OFÍCIO JUDICIAL' },
  { acao: '62', nome: 'PROCESSO EM SEGREDO DE JUSTIÇA (PENDENTE IDENTIFICAÇÃO)' },
  { acao: '63', nome: 'TRIBUNAL DE JUSTIÇA INDISPONÍVEL (PENDENTE DE IDENTIFICAÇÃO)' },
].sort((a, b) => a.nome.localeCompare(b.nome));

const tipoCausaPedir = [
  { causaPedir: '1', nome: 'NÃO RECONHECIMENTO DO FIDC COMO CREDOR' },
  { causaPedir: '5', nome: 'PAGAMENTO JUNTO AO CEDENTE' },
  { causaPedir: '6', nome: 'MANUTENÇÃO INDEVIDA PELO FIDC EM ÓRGÃO DE PROTEÇÃO AO CRÉDITO' },
  { causaPedir: '12', nome: 'OUTROS (ESPECIFICAR NO DETALHAMENTO DO OBJETO)' },
  { causaPedir: '16', nome: 'REVISÃO DO DÉBITO' },
  { causaPedir: '11', nome: 'NÃO RECONHECIMENTO DO DÉBITO' },
  { causaPedir: '17', nome: 'COBRANÇA E RESS. - AUTO' },
  { causaPedir: '10', nome: 'AÇÃO ANTERIOR CONTRA O CEDENTE' },
  { causaPedir: '7', nome: 'SUSPEITA DE FRAUDE' },
  { causaPedir: '18', nome: 'COBRANÇA E RESS. - RIC' },
  { causaPedir: '20', nome: 'COBRANÇA E RESS. - SAUDE' },
  { causaPedir: '19', nome: 'COBRANÇA E RESS. - VIDA' },
  { causaPedir: '21', nome: 'COBRANÇA E RESS. - OUTROS' },
  { causaPedir: '28', nome: 'ALEGA O NÃO ENVIO DOS BOLETOS' },
  { causaPedir: '23', nome: 'INDENIZAÇÃO TRABALHISTA' },
  { causaPedir: '27', nome: 'COBRANÇA NA PESSOA DIVERSA DO DEVEDOR' },
  { causaPedir: '24', nome: 'MANUTENÇÃO INDEVIDA PELO CEDENTE EM ÓRGÃO DE PROTEÇÃO AO CRÉDITO' },
  { causaPedir: '25', nome: 'CONTRATO DIVERGENTE' },
  { causaPedir: '26', nome: 'CONTRATO LIQUIDADO' },
  { causaPedir: '29', nome: 'NEGOCIAÇÃO/MANUTENÇÃO DO ACORDO' },
  { causaPedir: '32', nome: 'TÍTULO PRESCRITO' },
  { causaPedir: '34', nome: 'MENSAGENS ABUSIVAS (SMS)' },
  { causaPedir: '30', nome: 'BAIXA DE GRAVAME' },
  { causaPedir: '33', nome: 'COBRANÇA ABUSIVA (ATENDIMENTO TELEFÔNICO)' },
  { causaPedir: '31', nome: 'BAIXA DE PROTESTO' },
  { causaPedir: '42', nome: 'PROCESSO EM SEGREDO DE JUSTIÇA (PENDENTE IDENTIFICAÇÃO)' },
  { causaPedir: '39', nome: 'OFÍCIO: SOLICITAÇÃO DE INFORMAÇÕES DA DÍVIDA' },
  { causaPedir: '45', nome: 'BOLETO FRAUDADO' },
  { causaPedir: '46', nome: 'ALEGAÇÃO DE AMEAÇA DE BLOQUEIO DE CNH' },
  { causaPedir: '36', nome: 'RENEGOCIAÇÃO DE DÍVIDA - LEI SUPERENDIVIDAMENTO' },
  { causaPedir: '48', nome: 'TRIBUNAL DE JUSTIÇA INDISPONÍVEL (PENDENTE DE IDENTIFICAÇÃO)' },
  { causaPedir: '50', nome: 'PROTESTO INDEVIDO' },
].sort((a, b) => a.nome.localeCompare(b.nome));

const tipoEmpresaFundo = [
  { EmpresaFundo: '1', nome: 'FIDC CREDITSTORE' },
  { EmpresaFundo: '2', nome: 'FIDC IPANEMA' },
  { EmpresaFundo: '8', nome: 'FIDCIpanema VI' },
  { EmpresaFundo: '5', nome: 'FIDC IPANEMA II' },
  { EmpresaFundo: '4', nome: 'FIDEICOMISO FINANCEIRO VELUM OVERSEAS I' },
  { EmpresaFundo: '7', nome: 'FIDC IPANEMA V' },
  { EmpresaFundo: '6', nome: 'FIDC IPANEMA III' },
  { EmpresaFundo: '9', nome: 'IPANEMA EMPREENDIMENTOS' },
  { EmpresaFundo: '3', nome: 'VELUM CREDIT MANAGEMENT' },
  { EmpresaFundo: '10', nome: 'Santander (Financeira)' },
  { EmpresaFundo: '11', nome: 'Santander (Banco)' },
  { EmpresaFundo: '12', nome: 'FIDC ATACADO NRA' },
].sort((a, b) => a.nome.localeCompare(b.nome));

const tipoJustica = [
  { nome: 'JUSTIÇA COMUM', tipoJustica: '1' },
  { nome: 'JUIZADO ESPECIAL CÍVEL', tipoJustica: '2' },
  { nome: 'PROCON', tipoJustica: '3' },
  { nome: 'ÓRGÃO ADMINISTRATIVO', tipoJustica: '4' },
  { nome: 'JUSTIÇA DO TRABALHO', tipoJustica: '5' },
].sort((a, b) => a.nome.localeCompare(b.nome));

const tipoDescricao = [
  'O(a) autor(a) realizou um acordo com a ré e até o presente momento não houve a baixa bancária na instituição financeira, bem como o nome do(a) autor(a) permanece negativado nos órgão de proteção ao crédito por uma dívida paga.',
  'O(a) autor(a) teve seu nome inscrito nos órgãos de proteção ao crédito pela ré, porém o(a) mesmo(a) desconhece a dívida, entendendo serem indevidas tais cobranças.',
  'O(a) autor(a) alega que teve seu nome inscrito nos órgãos de proteção ao crédito e que, passados mais de cinco anos, seu nome permanece restrito. Por isso, requer que o seu nome seja excluído dos referidos cadastros.',
  'Aduz o(a) autor(a) que teve seu nome inscrito nos órgãos de proteção ao crédito pela ré, porém nunca foi sequer notificada sobre a referida dívida, nem tampouco, se recorda de sua origem, tendo dúvidas de sua existência e de sua exatidão.',
  'Alega o(a) autor(a) que teve ciência de uma dívida em seu nome, possivelmente, tenha sido vítima de fraude ao seu bom nome, com a inscrição indevida de seu nome em órgão restritivo de crédito pela ré, podendo sofrer outras anotações indevidas (fraudulentas por negócio jurídico realizado em seu nome por terceiros estranhos). Por tais razões, o(a) autor(a) nega ser devedor da ré.',
  'Trata-se de ofício, tomar providências.',
].sort((a, b) => a.localeCompare(b));

const ufs = [
  { idUF: '2', nome: 'AC' },
  { idUF: '7', nome: 'CE' },
  { idUF: '3', nome: 'AL' },
  { idUF: '6', nome: 'BA' },
  { idUF: '8', nome: 'DF' },
  { idUF: '4', nome: 'AP' },
  { idUF: '5', nome: 'AM' },
  { idUF: '10', nome: 'ES' },
  { idUF: '11', nome: 'MA' },
  { idUF: '9', nome: 'GO' },
  { idUF: '15', nome: 'PA' },
  { idUF: '12', nome: 'MT' },
  { idUF: '14', nome: 'MG' },
  { idUF: '17', nome: 'PR' },
  { idUF: '13', nome: 'MS' },
  { idUF: '18', nome: 'PE' },
  { idUF: '16', nome: 'PB' },
  { idUF: '20', nome: 'RJ' },
  { idUF: '19', nome: 'PI' },
  { idUF: '21', nome: 'RN' },
  { idUF: '22', nome: 'RS' },
  { idUF: '24', nome: 'RR' },
  { idUF: '28', nome: 'TO' },
  { idUF: '25', nome: 'SP' },
  { idUF: '23', nome: 'RO' },
  { idUF: '27', nome: 'SE' },
  { idUF: '26', nome: 'SC' },
].sort((a, b) => a.nome.localeCompare(b.nome));

export const picklist =  {
  ufs,
  tipoAcao,
  tipoCausaPedir,
  tipoEmpresaFundo,
  tipoJustica,
  tipoDescricao,
}
